apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-app
spec:
  selector:
    matchLabels:
      app: postgres-app
  template:
    metadata:
      labels:
        app: postgres-app
    spec:
      containers:
      - name: postgres-app
        image: postgres:latest
        ports:
        - containerPort: 5432
        envFrom: 
          - configMapRef: 
              name: postgres-configmap

# kubectl apply -f postgres-deploy.yaml