apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        image:  nginx:latest
        resources:
          requests:
             cpu: 250m
             memory: "512Mi"
          limits:
             cpu: 500m
             memory: "1Gi"
        ports:
        - containerPort: 80