apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-configmap
data:
# there are four symbol : >,>- , | , |-
  index.html: |-
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <h1 style="text-align: center;"> Welcome to DevOps Class </h1>
    </body>
    </html>