apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
# override the index page of nginx , which index.html is retrieved from configmap 
    spec:
      containers:
      - name: nginx-app
        image: nginx:latest 
        ports:
        - containerPort: 80
        volumeMounts: 
          - name: my-vol
            mountPath: /usr/share/nginx
      volumes: 
          - name: my-vol
            configMap: 
              name: nginx-index-configmap
              items: 
              - key: index.html
                path: html/index.html
