# clusterIP, nodePort, lb 
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: earthdx-app
spec:
  selector:
    matchLabels:
      app: earthdx-app
  template:
    metadata:
      labels:
        app: earthdx-app
    spec:
      containers:
      - name: earthdx-app-container
        image: 69966/earthdx:78
        ports:
        - containerPort: 80

# Used kubernetes service in order to expose or allow client to access your deployment 
---
apiVersion: v1
kind: Service
metadata:
  name: earthdx-service
spec:
  type: NodePort
  selector:
    app: earthdx-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001

# kubectl apply -f earthdx-deployment.yaml
# kubectl get service
# kubectl get deploy
