# clusterIP, nodePort, lb 
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app-container
        image: nginx:latest
        ports:
        - containerPort: 80

# Used kubernetes service in order to expose or allow client to access your deployment 
---
apiVersion: v1
kind: Service
metadata:
  name: mynginx-service
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000

# kubectl apply -f nginx-service.yaml
# kubectl get service
# kubectl get deploy
