services: 
  restful-api:
    image: restful-api-sample:v1.0.0
    container_name: spring_cont
    build: 
     context: . 
     dockerfile: dev.Dockerfile
     args: 
      - PORT=${APP_PORT:-8080}
    # environment: 
    pull_policy: build
    volumes: 
      - image-backup-vol:/app/filestorage/images
    ports: 
      - 8080:${APP_PORT:-8080}
  postgres:
    image: postgres:latest
    container_name: postgres_cont 
    environment: 
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes: 
      - postgres-data:/var/lib/postgresql/data
volumes: 
  image-backup-vol:
  postgres-data: 
