- name: Setup NFS Server 
  hosts: localhost
  become: yes
  vars_files: 
    - ../vars/default.yaml 
  roles:
    - nfs_server_setup


- name: Setup NFS Client 
  hosts: dev01,prod01 
  become: true 
  vars_files: 
    - ../vars/default.yaml 
  roles:
    - nfs_client_setup
