# Current Version (nginx )
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-blue 
  labels:
    app: demo-app
spec:
  replicas: 0
  # replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app 
        replicas: blue 
    spec:
      containers:
      - name: nginx-app-blue
        image: nginx:1.21
        ports:
        - containerPort: 80