# Our new version  ( reactjs )
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-green 
  labels:
    app: demo-app
spec:
  replicas: 4 
  # replicas: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app 
    spec:
      containers:
      - name: react-app-green
        image: 69966/earthdx:78
        ports:
        - containerPort: 80