# 10.184.0.2 -> worker2
# 10.148.0.6 -> worker 1
# 10.148.0.3 -> nfs server 
---
- name: Setup NFS Server 
  hosts: localhost
  become: yes

  vars: 
    nfs_remote_dir: /srv/nfs_shared
    nfs_client_ip1: 10.148.0.6
    nfs_client_ip2: 10.148.0.5
  tasks: 
    - name: Update APT caches 
      apt: 
        update_cache: yes 
    - name: Install NFS Kernel Server 
      apt: 
        name: nfs-kernel-server
        state: present 
    - name: Create Directory to used 
      file: 
        path: "{{ nfs_remote_dir }}"
        state: directory
        owner: nobody
        group: nogroup
        mode: "0777"
    # configuration inside /etc/exports ( tell which clients can use  it)
    - name: Write Config on /etc/exports
      lineinfile: 
        path: /etc/exports
        # line: " {{ nfs_remote_dir }} *(rw,sync,no_subtree_check,no_root_squash)"
        line: " {{ nfs_remote_dir }} {{nfs_client_ip1}}(rw,sync,no_subtree_check,no_root_squash)  {{nfs_client_ip2}}(rw,sync,no_subtree_check,no_root_squash)"
        state: present 
        create: yes 
    - name: Apply Configuration 
      command: exportfs -ra 
    - name: Restart NFS Kernel Service 
      systemd: 
        name: nfs-kernel-server
        enabled: true 
        state: restarted 

# ansible-playbook -i inventory.ini playbooks/nfs_server.yaml
# just run nfs_server