apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-uploader-app
spec:
  selector:
    matchLabels:
      app: spring-uploader-app
  template:
    metadata:
      labels:
        app: spring-uploader-app
    spec:
      containers:
      - name: spring-uploader-app
        #imagePullPolicy: IfNotPresent
        image: 69966/springgradleimg:1.1.1
        ports:
        - containerPort: 8080
        volumeMounts: 
          - name: image-storage 
            mountPath: app/src/main/resources/images
      volumes: 
          - name: image-storage
            persistentVolumeClaim: 
              claimName: spring-uploader-pvc   